metric_batch: "prometheus"
table_key: "metrics_prometheus"
ingest_cron_schedule: "*/5 * * * *"
train_cron_schedule: "*/180 * * * *"
score_cron_schedule: "*/10 * * * *"
alert_cron_schedule: "*/15 * * * *"
change_cron_schedule: "*/15 * * * *"
llmalert_cron_schedule: "*/60 * * * *"
plot_cron_schedule: "*/30 * * * *"
alert_always: False
alert_metric_timestamp_max_days_ago: 3
disable_llmalert: False
alert_methods: "email,slack"
ingest_fn: >
  {% include "./examples/prometheus/prometheus.py" %}
