version: "3.8"

services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  anomstack_postgresql:
    image: postgres:11
    container_name: anomstack_postgresql
    environment:
      POSTGRES_USER: "${ANOMSTACK_POSTGRES_USER:-postgres_user}"
      POSTGRES_PASSWORD: "${ANOMSTACK_POSTGRES_PASSWORD:-postgres_password}"
      POSTGRES_DB: "${ANOMSTACK_POSTGRES_DB:-postgres_db}"
    ports:
      - "${ANOMSTACK_POSTGRES_FORWARD_PORT:-}:5432"
    networks:
      - anomstack_network

  # This service runs the gRPC server that loads your user code, in both dagit
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by dagit.
  anomstack_code:
    build:
      context: .
      dockerfile: ./Dockerfile.anomstack_code
    container_name: anomstack_code
    image: anomstack_code_image
    restart: always
    volumes:
      # - ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}:/tmp/conf/gcp_credentials.json
      - ./tmp:/opt/dagster/app/tmp
      - ./tmpdata:/opt/dagster/app/tmpdata
    environment:
      DAGSTER_POSTGRES_USER: "${ANOMSTACK_POSTGRES_USER:-postgres_user}"
      DAGSTER_POSTGRES_PASSWORD: "${ANOMSTACK_POSTGRES_PASSWORD:-postgres_password}"
      DAGSTER_POSTGRES_DB: "${ANOMSTACK_POSTGRES_DB:-postgres_db}"
      DAGSTER_CURRENT_IMAGE: "anomstack_code_image"
      # read from .env file
      ANOMSTACK_GCP_PROJECT_ID: ${ANOMSTACK_GCP_PROJECT_ID}
      ANOMSTACK_SNOWFLAKE_ACCOUNT: ${ANOMSTACK_SNOWFLAKE_ACCOUNT}
      ANOMSTACK_SNOWFLAKE_USER: ${ANOMSTACK_SNOWFLAKE_USER}
      ANOMSTACK_SNOWFLAKE_PASSWORD: ${ANOMSTACK_SNOWFLAKE_PASSWORD}
      ANOMSTACK_SNOWFLAKE_WAREHOUSE: ${ANOMSTACK_SNOWFLAKE_WAREHOUSE}
      ANOMSTACK_AWS_ACCESS_KEY_ID: ${ANOMSTACK_AWS_ACCESS_KEY_ID}
      ANOMSTACK_AWS_SECRET_ACCESS_KEY: ${ANOMSTACK_AWS_SECRET_ACCESS_KEY}
      ANOMSTACK_DUCKDB_PATH: ${ANOMSTACK_DUCKDB_PATH}
      ANOMSTACK_TABLE_KEY: ${ANOMSTACK_TABLE_KEY}
      ANOMSTACK_MODEL_PATH: ${ANOMSTACK_MODEL_PATH}
      ANOMSTACK_SLACK_WEBHOOK_URL: ${ANOMSTACK_SLACK_WEBHOOK_URL}
      ANOMSTACK_IGNORE_EXAMPLES: ${ANOMSTACK_IGNORE_EXAMPLES}
      ANOMSTACK_ALERT_EMAIL_FROM: ${ANOMSTACK_ALERT_EMAIL_FROM}
      ANOMSTACK_ALERT_EMAIL_TO: ${ANOMSTACK_ALERT_EMAIL_TO}
      ANOMSTACK_ALERT_EMAIL_SMTP_HOST: ${ANOMSTACK_ALERT_EMAIL_SMTP_HOST}
      ANOMSTACK_ALERT_EMAIL_SMTP_PORT: ${ANOMSTACK_ALERT_EMAIL_SMTP_PORT}
      ANOMSTACK_ALERT_EMAIL_PASSWORD: ${ANOMSTACK_ALERT_EMAIL_PASSWORD}
      # ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: "/tmp/conf/gcp_credentials.json"
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON}
      ANOMSTACK_OPENAI_KEY: ${ANOMSTACK_OPENAI_KEY}
      ANOMSTACK_OPENAI_MODEL: ${ANOMSTACK_OPENAI_MODEL}
      ANOMSTACK_MAX_RUNTIME_SECONDS_TAG: ${ANOMSTACK_MAX_RUNTIME_SECONDS_TAG}
    networks:
      - anomstack_network

  # This service runs dagit, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  anomstack_dagit:
    build:
      context: .
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: anomstack_dagit
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "${ANOMSTACK_POSTGRES_USER:-postgres_user}"
      DAGSTER_POSTGRES_PASSWORD: "${ANOMSTACK_POSTGRES_PASSWORD:-postgres_password}"
      DAGSTER_POSTGRES_DB: "${ANOMSTACK_POSTGRES_DB:-postgres_db}"
      # read from .env file
      ANOMSTACK_GCP_PROJECT_ID: ${ANOMSTACK_GCP_PROJECT_ID}
      ANOMSTACK_SNOWFLAKE_ACCOUNT: ${ANOMSTACK_SNOWFLAKE_ACCOUNT}
      ANOMSTACK_SNOWFLAKE_USER: ${ANOMSTACK_SNOWFLAKE_USER}
      ANOMSTACK_SNOWFLAKE_PASSWORD: ${ANOMSTACK_SNOWFLAKE_PASSWORD}
      ANOMSTACK_SNOWFLAKE_WAREHOUSE: ${ANOMSTACK_SNOWFLAKE_WAREHOUSE}
      ANOMSTACK_AWS_ACCESS_KEY_ID: ${ANOMSTACK_AWS_ACCESS_KEY_ID}
      ANOMSTACK_AWS_SECRET_ACCESS_KEY: ${ANOMSTACK_AWS_SECRET_ACCESS_KEY}
      ANOMSTACK_DUCKDB_PATH: ${ANOMSTACK_DUCKDB_PATH}
      ANOMSTACK_TABLE_KEY: ${ANOMSTACK_TABLE_KEY}
      ANOMSTACK_MODEL_PATH: ${ANOMSTACK_MODEL_PATH}
      ANOMSTACK_SLACK_WEBHOOK_URL: ${ANOMSTACK_SLACK_WEBHOOK_URL}
      ANOMSTACK_IGNORE_EXAMPLES: ${ANOMSTACK_IGNORE_EXAMPLES}
      ANOMSTACK_ALERT_EMAIL_FROM: ${ANOMSTACK_ALERT_EMAIL_FROM}
      ANOMSTACK_ALERT_EMAIL_TO: ${ANOMSTACK_ALERT_EMAIL_TO}
      ANOMSTACK_ALERT_EMAIL_SMTP_HOST: ${ANOMSTACK_ALERT_EMAIL_SMTP_HOST}
      ANOMSTACK_ALERT_EMAIL_SMTP_PORT: ${ANOMSTACK_ALERT_EMAIL_SMTP_PORT}
      ANOMSTACK_ALERT_EMAIL_PASSWORD: ${ANOMSTACK_ALERT_EMAIL_PASSWORD}
      # ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: "/tmp/conf/gcp_credentials.json"
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON}
      ANOMSTACK_OPENAI_KEY: ${ANOMSTACK_OPENAI_KEY}
      ANOMSTACK_OPENAI_MODEL: ${ANOMSTACK_OPENAI_MODEL}
      ANOMSTACK_MAX_RUNTIME_SECONDS_TAG: ${ANOMSTACK_MAX_RUNTIME_SECONDS_TAG}
    volumes: # Make docker client accessible so we can terminate containers from dagit
      # - ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}:/tmp/conf/gcp_credentials.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./tmp:/opt/dagster/app/tmp
      - ./tmpdata:/opt/dagster/app/tmpdata
    networks:
      - anomstack_network
    depends_on:
      - anomstack_postgresql
      - anomstack_code

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  anomstack_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: anomstack_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "${ANOMSTACK_POSTGRES_USER:-postgres_user}"
      DAGSTER_POSTGRES_PASSWORD: "${ANOMSTACK_POSTGRES_PASSWORD:-postgres_password}"
      DAGSTER_POSTGRES_DB: "${ANOMSTACK_POSTGRES_DB:-postgres_db}"
      # read from .env file
      ANOMSTACK_GCP_PROJECT_ID: ${ANOMSTACK_GCP_PROJECT_ID}
      ANOMSTACK_SNOWFLAKE_ACCOUNT: ${ANOMSTACK_SNOWFLAKE_ACCOUNT}
      ANOMSTACK_SNOWFLAKE_USER: ${ANOMSTACK_SNOWFLAKE_USER}
      ANOMSTACK_SNOWFLAKE_PASSWORD: ${ANOMSTACK_SNOWFLAKE_PASSWORD}
      ANOMSTACK_SNOWFLAKE_WAREHOUSE: ${ANOMSTACK_SNOWFLAKE_WAREHOUSE}
      ANOMSTACK_AWS_ACCESS_KEY_ID: ${ANOMSTACK_AWS_ACCESS_KEY_ID}
      ANOMSTACK_AWS_SECRET_ACCESS_KEY: ${ANOMSTACK_AWS_SECRET_ACCESS_KEY}
      ANOMSTACK_DUCKDB_PATH: ${ANOMSTACK_DUCKDB_PATH}
      ANOMSTACK_TABLE_KEY: ${ANOMSTACK_TABLE_KEY}
      ANOMSTACK_MODEL_PATH: ${ANOMSTACK_MODEL_PATH}
      ANOMSTACK_SLACK_WEBHOOK_URL: ${ANOMSTACK_SLACK_WEBHOOK_URL}
      ANOMSTACK_IGNORE_EXAMPLES: ${ANOMSTACK_IGNORE_EXAMPLES}
      ANOMSTACK_ALERT_EMAIL_FROM: ${ANOMSTACK_ALERT_EMAIL_FROM}
      ANOMSTACK_ALERT_EMAIL_TO: ${ANOMSTACK_ALERT_EMAIL_TO}
      ANOMSTACK_ALERT_EMAIL_SMTP_HOST: ${ANOMSTACK_ALERT_EMAIL_SMTP_HOST}
      ANOMSTACK_ALERT_EMAIL_SMTP_PORT: ${ANOMSTACK_ALERT_EMAIL_SMTP_PORT}
      ANOMSTACK_ALERT_EMAIL_PASSWORD: ${ANOMSTACK_ALERT_EMAIL_PASSWORD}
      # ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: "/tmp/conf/gcp_credentials.json"
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON}
      ANOMSTACK_OPENAI_KEY: ${ANOMSTACK_OPENAI_KEY}
      ANOMSTACK_OPENAI_MODEL: ${ANOMSTACK_OPENAI_MODEL}
      ANOMSTACK_MAX_RUNTIME_SECONDS_TAG: ${ANOMSTACK_MAX_RUNTIME_SECONDS_TAG}
    volumes: # Make docker client accessible so we can launch containers using host docker
      # - ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}:/tmp/conf/gcp_credentials.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./tmp:/opt/dagster/app/tmp
      - ./tmpdata:/opt/dagster/app/tmpdata
    networks:
      - anomstack_network
    depends_on:
      - anomstack_postgresql
      - anomstack_code

  # This service runs the Streamlit dashboard
  anomstack_dashboard:
    build:
        context: .
        dockerfile: ./Dockerfile.anomstack_dashboard
    container_name: anomstack_dashboard
    ports:
      - "8501:8501"
    environment:
      # read from .env file
      ANOMSTACK_GCP_PROJECT_ID: ${ANOMSTACK_GCP_PROJECT_ID}
      ANOMSTACK_SNOWFLAKE_ACCOUNT: ${ANOMSTACK_SNOWFLAKE_ACCOUNT}
      ANOMSTACK_SNOWFLAKE_USER: ${ANOMSTACK_SNOWFLAKE_USER}
      ANOMSTACK_SNOWFLAKE_PASSWORD: ${ANOMSTACK_SNOWFLAKE_PASSWORD}
      ANOMSTACK_SNOWFLAKE_WAREHOUSE: ${ANOMSTACK_SNOWFLAKE_WAREHOUSE}
      ANOMSTACK_AWS_ACCESS_KEY_ID: ${ANOMSTACK_AWS_ACCESS_KEY_ID}
      ANOMSTACK_AWS_SECRET_ACCESS_KEY: ${ANOMSTACK_AWS_SECRET_ACCESS_KEY}
      ANOMSTACK_DUCKDB_PATH: ${ANOMSTACK_DUCKDB_PATH}
      ANOMSTACK_TABLE_KEY: ${ANOMSTACK_TABLE_KEY}
      ANOMSTACK_IGNORE_EXAMPLES: ${ANOMSTACK_IGNORE_EXAMPLES}
      # ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: "/tmp/conf/gcp_credentials.json"
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}
      ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON: ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS_JSON}
      ANOMSTACK_MAX_RUNTIME_SECONDS_TAG: ${ANOMSTACK_MAX_RUNTIME_SECONDS_TAG}
    volumes:
      # - ${ANOMSTACK_GOOGLE_APPLICATION_CREDENTIALS}:/tmp/conf/gcp_credentials.json
      - ./tmp:/opt/dagster/app/tmp
      - ./tmpdata:/opt/dagster/app/tmpdata
    command: streamlit run /opt/dagster/app/dashboard.py --server.port 8501
    networks:
      - anomstack_network
    profiles:
      - "dashboard"

networks:
  anomstack_network:
    driver: bridge
    name: anomstack_network
