# theme: jekyll-theme-minimal
title: Anomstack
description: Painless open source anomaly detection for your metrics! 📈📉🚀

layout: page
permalink: /bigquery

layout: page
permalink: /snowflake

layout: page
permalink: /gcs

layout: page
permalink: /s3

layout: page
permalink: /deployment/gcp