# theme: jekyll-theme-minimal
title: Anomstack
description: Painless open source anomaly detection for your metrics! 📈📉🚀

layout: page
title: "BigQuery"
permalink: /bigquery

layout: page
title: "Snowflake"
permalink: /snowflake
